### ISSUE TITLE
why you add relu and use 2 maxpooling( origin is 4 maxpooling),why are you do that? is perfrom better than orgin?

### ISSUE THREAD

**Issue by dotsonliu** [TJCVRS/CRNN_Tensorflow#1]
hello, i see Baoguang Shi's origin paper ,the origin paper is:
@TJCVRS  ![image](https://user-images.githubusercontent.com/28289146/31379266-5a57f220-ade0-11e7-8871-c1548853f1b7.png)

your's :
![image](https://user-images.githubusercontent.com/28289146/31379242-4ec73236-ade0-11e7-9dc9-702fda904728.png)

you add relu and use 2 maxpooling( origin is 4 maxpooling),why are you do that? is perfrom better than orgin?

**Comment by TJCVRS** [comment]
@dotsonliu sorry for the delayed replying. I use the same cnn architecture mentioned in the original paper. You can find the two other maxpooling layer in self.__conv_stage function. As for the relu layer it is a basic option to activate the neuron

**Comment by CXY573** [comment]
@dotsonliu  have you trained your own model use synth dataset？？？
