### ISSUE TITLE
卷积

### ISSUE THREAD

**Issue by CXY573** [TJCVRS/CRNN_Tensorflow#10]
conv = self.conv2d(inputdata=inputdata, out_channel=out_dims, kernel_size=3, stride=1, use_bias=False, name=name)
这句话，为什么可以直接self.conv2d，self不是代表类吗，crnn中的，然后直接定义一个conv2d，不用调用tf.nn.conv2d来定义？？？
还有
conv1 = self.__conv_stage(inputdata=inputdata, out_dims=64, name='conv1')  # batch*16*50*64
原本是32*100，池化后变成16*50是没问题，但是卷积之后大小不变应该是因为conv2d里面有一个padding='SAME'吧，但是你这里都没有padding参数，论文里好像是1×1

**Comment by CXY573** [comment]
奥，我看到cnn_basenet的文件了，我发现你的CNN跟原文不太一样～
比如bn的位置，还有就是比如第三个池化的stride 还有Kernel都跟原文有不一样的细微变化 【2，2】->【2,1】

**Comment by CXY573** [comment]
还有 就是对类不太熟悉，在crnn_model中好像没有出现跟cnn_basenet有继承或者申明之类的关系，为什么直接在crnn里面用self.conv2d就可以调用cnn_basenet的函数，虽然我看到了import cnn_basenet，但是在crnn中的self不是指向crnn中ShadowNet这个类本身吗，怎么self.conv2d是指向cnn_basenet，希望得到解疑

**Comment by TJCVRS** [comment]
@CXY573 这个你可以查看一下关于python的书籍

**Comment by CXY573** [comment]
好吧，那你的CNN跟原文不太一样～
比如bn的位置，还有就是比如第三个池化的stride 还有Kernel都跟原文有不一样的细微变化 【2，2】->【2,1】，是有更好的效果还是说细微的差别对于特征提取没有什么影响？？？

**Comment by TJCVRS** [comment]
@CXY573 和原文不一样主要可能是实现框架不同，但是需要达到的目的是统一的
