### ISSUE TITLE
准确率公式  if len(pred) == 0:    accuracy.append(1)

### ISSUE THREAD

**Issue by CXY573** [TJCVRS/CRNN_Tensorflow#11]
for index, gt_label in enumerate(gt_labels):
                pred = preds[index]#预测的标签
                totol_count = len(gt_label)#真是标签的长度
                correct_count = 0
                try:
                    for i, tmp in enumerate(gt_label):
                        if tmp == pred[i]:#计算预测的对的字符格式
                            correct_count += 1
                except IndexError:
                    continue
                finally:
                    try:
                        accuracy.append(correct_count / totol_count)
                    except ZeroDivisionError:
                        if len(pred) == 0:
                            accuracy.append(1)
                        else:
                            accuracy.append(0)
            accuracy = np.mean(np.array(accuracy).astype(np.float32), axis=0)
##############################################################################
这是train_shadownet里面关于accuracy的计算，if len(pred) == 0:    accuracy.append(1)，这句话有问题把，pred是预测的标签，长度为0，为什么准确率的计算加了1？？？？？？预测为0，准确率应该加0啊。。。

**Comment by CXY573** [comment]
这是一个很重要的问题呀～～～～～～～
还有请问你是把整个数据集放进去训练了吗。。。722万张图片啊

**Comment by TJCVRS** [comment]
@CXY573 你可能没有仔细看代码，我的意思是如果标签长度为0并且预测长度也为0那么正确加1，否则错误加1.关于数据集，我已经在readme里面说了我用了一部分Synth90K数据集，因为客观条件限制。后续我会更改dataprovider方法来支持更大数据量。

**Comment by CXY573** [comment]
嗯 太大数据应该跑不进去，我在尝试分成几个tfrecord 然后按队列读取，如果可以这样做我会告诉你～

**Comment by TJCVRS** [comment]
@CXY573 好的
