### ISSUE TITLE
Error while  first time running!

### ISSUE THREAD

**Issue by anjanna535** [TJCVRS/CRNN_Tensorflow#12]
![screenshot 190](https://user-images.githubusercontent.com/20242048/32831827-9390feb4-ca1f-11e7-828a-b7684ed0e24d.png)
i want to use it for my mini project in my college...so please help me by resolving this error...

**Comment by TJCVRS** [comment]
@anjanna535 You can solve it by adding the module path into your python path

**Comment by anjanna535** [comment]
how can i do that

**Comment by TJCVRS** [comment]
@anjanna535 Or just add sys.path.append(os.getcwd()) on the top of the scripts

**Comment by anjanna535** [comment]
I added that but still having module...error

**Comment by TJCVRS** [comment]
@anjanna535 Did you run the code on the root folder?

**Comment by CXY573** [comment]
If you don't know how to slove the problem.You can just put all the “.py” files，including crnn_model.py,data_provide.py into the "tools" floder.And you will find that the code can work!

**Comment by CXY573** [comment]
@anjanna535
