### ISSUE TITLE
识别率

### ISSUE THREAD

**Issue by CXY573** [TJCVRS/CRNN_Tensorflow#15]
你好，原文在synth上的识别率应该是达到了90多的 但是我最高的识别率仅88%，网络已经收敛，但是最后的识别率一直稳定不下来，识别率也跟原文差距颇大，请问是哪里出错了吗

**Comment by CXY573** [comment]
训练数据是400万张，应该不存在过拟合的现象

**Comment by CXY573** [comment]
顺便提一个建议 输出的Epoch 应该是step把，Epoch应该是把输入数据跑一遍才算一个吧，这个应该是跑一个batch size的step

**Comment by TJCVRS** [comment]
@CXY573 OK

**Comment by xrf116** [comment]
@CXY573 我中文5000字，30万张图片训练了快一周，都才30%左右，你88%是中文么？

**Comment by CXY573** [comment]
@xrf116 肯定是英文啊，中文？你改了输出类别么，37个类别训练中文的话，效果可想而知把，这算法感觉并不适合中文呀

**Comment by TJCVRS** [comment]
@xrf116 我训练中文也是收敛速度很慢，现在还在想办法解决这个问题

**Comment by xrf116** [comment]
改了，之前用车牌试过。2天就到96%，现在换成5000多字中文。基本就动不了。我在想是不是要先一个字一个字的训练一次再end-to-end

**Comment by TJCVRS** [comment]
@xrf116 我现在就是先训练了CNN然后在训练后面的lstm感觉还是比较慢

**Comment by CXY573** [comment]
@TJCVRS @xrf116 请问1_Recommencement_63225.jpg  图片里的名字63225代表的是什么，我想用ICDAR2013数据集，但是不能成功，想知道这个数字的意义是什么
