### ISSUE TITLE
突然发现个问题，我的gpu使用率是0，你们有遇见吗？

### ISSUE THREAD

**Issue by xrf116** [TJCVRS/CRNN_Tensorflow#16]
![image](https://user-images.githubusercontent.com/32292812/33362031-77f5d7aa-d515-11e7-8846-c9aee1f3b5cc.png)

@TJCVRS 你是这样现象吗？GPU内存用了4G但是使用率却是0，难怪训练这么慢

**Comment by TJCVRS** [comment]
@xrf116 有这样的问题 你可以参考一下这个https://github.com/tensorflow/tensorflow/issues/543

**Comment by TJCVRS** [comment]
@xrf116 长时间观察GPU使用率可以发现GPU使用率时高时低 这个应该是正常现象

**Comment by xrf116** [comment]
我知道原因了。我修改了代码
 for epoch in range(train_epochs):
            _, c = sess.run([optimizer, cost])
            print('Epoch: {:d} cost= {:9f}' .format(epoch , c))
            if epoch % 500 == 0:
                seq_distance, preds, gt_labels, summary = sess.run(
                    [ sequence_dist, decoded, input_labels, merge_summary_op])
seq_distance, preds非常耗时，但是对于训练来说好像作用没那么大，这样训练速度应该会提升，并且gpu利用率也上来了
![image](https://user-images.githubusercontent.com/32292812/33415337-d9f50e2e-d5d0-11e7-83ef-ece157f470d8.png)

**Comment by TJCVRS** [comment]
@xrf116 上面那两个计算对训练参数没有什么用，只是为了监控训练过程。不过这两个计算对GPU使用率影响不大，你不计算那两个参数也没有问题。

**Comment by xrf116** [comment]
嗯，干掉后，训练速度提升了很多

**Comment by caslei** [comment]
@xrf116 仅仅是训练代码的问题吗？我也遇到这个问题，同样的代码在笔记本(gtx1060)上跑的比台式机(2080ti)快？很奇怪？
