### ISSUE TITLE
ICDAR2013

### ISSUE THREAD

**Issue by CXY573** [TJCVRS/CRNN_Tensorflow#17]
请问谁用过ICDAR2013数据集，其中包含了特殊字符（），！，？等，导致CTC做loss的时候跟labels一直不匹配，因为输出类别只有37类，但是现在不止37类了，请问你们是怎么解决的

**Comment by xrf116** [comment]
num_classes=5530) 这里
![Uploading image.png…]()   还有这里

**Comment by CXY573** [comment]
直接改类别的大小会疯狂降识别率把，而且原文也是分37类啊

**Comment by CXY573** [comment]
@xrf116

**Comment by xrf116** [comment]
类别越多识别难度越大。改了以后应该是需要重新训练

**Comment by TJCVRS** [comment]
@CXY573 新数据需要重新修改类别信息 然后重新训练模型

**Comment by CXY573** [comment]
@TJCVRS 我是把特殊字符变成空白了，但是识别率只有20%，有谁知道怎么做吗，用了数据增强，调了很久参，完全没有作用呀。。。。。

**Comment by CXY573** [comment]
@xrf116 你试过ICDAR2013吗，识别率只有可怜的20%.。。过拟合严重

**Comment by CXY573** [comment]
除了改num_classes=5530) 这里， 还要改哪里，我看不到图片@xrf116

**Comment by CXY573** [comment]
InvalidArgumentError (see above for traceback): Saw a non-null label (index >= num_classes - 1) following a null label, batch: 10 num_classes: 62 labels: 4,18,15,0
我把类别改大后，出现这个错误，ICDAR中含有括号，问号之类的@TJCVRS，@xrf116

**Comment by xrf116** [comment]
data/char_dicr里面有两个json文件，要把需要支持的字符添加进去。然后就是 num_classes改成你想支持的类别数量+1

**Comment by xrf116** [comment]
我也是看作者代码。我也刚接触深度学习一个月不到

**Comment by CXY573** [comment]
直接加进去吗？编码是随便赋值么？@xrf116

**Comment by CXY573** [comment]
InvalidArgumentError (see above for traceback): Saw a non-null label (index >= num_classes - 1) following a null label, batch: 8 num_classes: 49 labels: 4,18,15,0
不行，类别改了，字典改了，但是还是这样@TJCVRS，@xrf116

**Comment by xrf116** [comment]
这个应该是 模型的类别不对，少了

**Comment by xrf116** [comment]
编码，作者写了一个转化的。在text.py里面

**Comment by CXY573** [comment]
@xrf116 你用的别的数据库是多大，ICDAR3才1000张图片，过拟合相当严重

**Comment by TJCVRS** [comment]
@CXY573 1000张图像很容易过拟合

**Comment by CXY573** [comment]
@TJCVRS 问题是文章里是有89.6的识别率，我想试试，可是怎么都不行，就算用了原来预训练的synth的模型接着跑，最终也只有74%最高一次的识别率

**Comment by hufangjian** [comment]
问题解决了吗？我要遇到了同样的问题，我是识别中文的，char_dit 里面有5529个字符，numclass 改成了5530还是出现同样的错误。也重新生成了json文件。
