### ISSUE TITLE
如何在训练的同时进行测试

### ISSUE THREAD

**Issue by ZhouFangru** [TJCVRS/CRNN_Tensorflow#18]
你好，
    请问如何在训练的同时进行测试呢，我本来打算利用placeholder，在Session里面feed_dict不同的数据（训练和测试），可是每个图片的标签好像是不一样大小。

**Comment by ZhouFangru** [comment]
另外，批量测试是不是所有的图片大小要一样才行，因为生成tfrecors的文件好像要求所有图片大小一样。

**Comment by TJCVRS** [comment]
@ZhouFangru 你说的测试是指validation过程还是单纯的inference呢？

**Comment by ZhouFangru** [comment]
我是想请教在训练的过程中（迭代了__C.TRAIN.TEST_DISPLAY_STEP次以后），输出验证结果。
另外，如果我单独运行test_shadownet.py文件进行批量测试，发现测试的速度和训练速度相似（测试一个batch=32和训练一个batch=32所花时间相同），这是为什么呢，测试没有返传，速度不应该更快吗？

**Comment by TJCVRS** [comment]
@ZhouFangru 我这里测试没有出现测试速度和训练速度相似的问题==！

**Comment by ZhouFangru** [comment]
那请问您一张图片的训练时间和测试时间分别为多少呢？
