### ISSUE TITLE
cost一直下不去

### ISSUE THREAD

**Issue by xrf116** [TJCVRS/CRNN_Tensorflow#19]
@TJCVRS 我用crnn训练中文，5300类别。ctc_loss一直下不去，感觉就识别率在35%左右就不动了。。如何破？有什么好的建议么？

**Comment by TJCVRS** [comment]
@xrf116 我现在也在解决这个训练速度的问题==！ 暂时还没有解决，只能长时间训练==！

**Comment by TJCVRS** [comment]
@xrf116 不知道你训练使用的训练样本量大概是多少？

**Comment by xrf116** [comment]
class_5000个汉字,每个字200个图片左右

**Comment by TJCVRS** [comment]
@xrf116 那应该收敛速度会快一些，不过可能会出现过拟合

**Comment by CXY573** [comment]
@xrf116 你好，中文的数据库可以发个链接给我么
