### ISSUE TITLE
用代码里面shadownet_2017-10-17-11-47-46.ckpt-19999运行demo，识别率几乎是0

### ISSUE THREAD

**Issue by xrf116** [TJCVRS/CRNN_Tensorflow#2]
能共享一下之前训练的数据么？谢谢

**Comment by TJCVRS** [comment]
@xrf116 非常感谢提醒，之前修改了部分字典建立的函数忘了上传新代码，导致解析label的时候出现错误识别错误，这个不是训练模型的问题是显示的问题。现在重新上传了新的代码，你可以重新测试一下，应该没有问题。至于训练数据就是ReadMe里写了的Synth_90K数据集，新模型是使用其中的250万张样本训练的，生成的tfrecords太大不好上传至github。我代码里写了工具你可以自行下载该数据集然后生成相应的tfrecords。有什么其他问题欢迎讨论。

**Comment by xrf116** [comment]
ok,可以了，谢谢
