### ISSUE TITLE
批量测试不同大小的图片和sequence_length大小设置的问题

### ISSUE THREAD

**Issue by Tower0823** [TJCVRS/CRNN_Tensorflow#20]
作者你好~麻烦请教两个问题：

**1. 如何批量测试不同大小的图片？**
1）因为测试图像大小比例均不同，转为tfrecords过程中resize造成图像变形会影响准确率，因而想直接拿图像测试。但不同大小的图像每次build_shadownet的网络都不同，测试第一张图像后已经创建了，却又不能reuse，而tf.variabel_scope是共享变量，如何释放啊？╮(╯_╰)╭
2）若tf.variabel_scope释放成功（或者用shell写循环调用demo_shadownet或者batch size=1的test_shadownet）每测试一张图像都要重新build网络，速度很慢啊，作者有啥好建议吗~
`
        with tf.variable_scope('shadow'):
            net_out = net.build_shadownet(inputdata=inputdata)`
![image](https://user-images.githubusercontent.com/33520406/33715124-78179782-db8c-11e7-9e33-562af5f95681.png)

2. sequence_length=25*np.ones(32)
**对seqence_length应该怎么理解？**
 

> cnn输出512个大小为25的*1的特征图，可以理解为25个长度512的序列吗，经过rnn输出对应25帧长的预测序列（未合并）？为什么选择25呢，25和原图大小或者说cnn输出的特征图大小有关吗？我在训练中文行识别时，图像长宽比例较大，输入图像归一化为(280,32)，cnn的输出应为70，当时没有改 sequence_length, 还是保持25为啥也没有报错啊？

**Comment by TJCVRS** [comment]
@Tower0823 这个25是预先设置的超参数 是你自己可以调整的。这个模型的输入是需要归一化的 不能输入不同尺寸的图像

**Comment by Tower0823** [comment]
噢好的，谢谢作者！那这个超参数是只需要大于最后预测的序列包含字符的个数就行了吗？

**Comment by Tower0823** [comment]
噢好的，谢谢作者！那这个25只需要大于预测序列的字符个数就行了吗？和cnn的输出没有关系对吧？

**Comment by TJCVRS** [comment]
@Tower0823 是的 这个25需要大于预测序列的字符数
