### ISSUE TITLE
Could we use this library in android?

### ISSUE THREAD

**Issue by mavyasoni786** [TJCVRS/CRNN_Tensorflow#23]
Hello,

I need real-time OCR in my application. Could I use your library on Android? 

Thank!

**Comment by TJCVRS** [comment]
@mavyasoni786 The model can not be directly used in android

**Comment by ibraheemalkilanny** [comment]
@mavyasoni786 On android you can use tesseract which is much better. Also one can convert almost any model to *.pb and load on android
