### ISSUE TITLE
I need number recogintion as well?

### ISSUE THREAD

**Issue by arsalan993** [TJCVRS/CRNN_Tensorflow#25]
I am unable to find a data set on which i can train it for recognizing numbers as well.
Can some one suggest me data set for that. 
If you have trained a model that can recognize both alphabets and numbers so let me know if you can provide me with your pre-trained model

**Comment by sahadev123** [comment]
Did you find anything related to recognizing both alphabets and numbers?

**Comment by mdbenito** [comment]
You can generate your own dataset easily with any of a number of available tools. Just google "synthetic text generator ocr" and pick the project that best suits your requirements
