### ISSUE TITLE
There are two types of data set at the link below. which one i should use.

### ISSUE THREAD

**Issue by arsalan993** [TJCVRS/CRNN_Tensorflow#29]
http://www.robots.ox.ac.uk/~vgg/data/text/

1. Synthetic Word Dataset

2. Character Datasets

On which one i should train on

**Comment by TJCVRS** [comment]
@arsalan993 The model has been trained on Synth dataset. You are welcomed to try any dataset you want.

**Comment by arsalan993** [comment]
"Synthetic Word Dataset" is basically the Synth data set am i right.. 
Btw i really like you implementation but issue is it is not trained to recognize number .. so tell me should the train again with a new data set for adding number recognizer feature into it.

**Comment by TJCVRS** [comment]
@arsalan993 In my opinion you'd better train a new model on your own dataset, if you just need to recognize numbers you can change the word dictionary into a new one that only contains numbers.

**Comment by arsalan993** [comment]
yes i am planning to merge COCO text recognition dataset with and synth90 dataset and will train my model on it.. 
In which files i should the word dictionary. 
Btw i want to recognize both alphabets and numbers.. 
please elaborate where exactly do i need to make changes
