### ISSUE TITLE
Text Extraction from Images

### ISSUE THREAD

**Issue by niyaz1996** [TJCVRS/CRNN_Tensorflow#38]
Hi,
 Is it possible to extract all the text(all words) rather than a single word available in the image using this code?If it is so,please let me know whether I have to tune and change the layer stack available.

**Comment by TJCVRS** [comment]
@niyaz1996 The model is not used to extract text region in a image but used to recognize the text itself.

**Comment by niyaz1996** [comment]
yes buddy,I understand but I just want to make sure whether this model will be able to recognize all the text within the given image.
Like,if I give the below image to this model,whether this will recognize all the text words.
The expected output is : **cyber ireland text,image,culture claire lynch**  
![book32](https://user-images.githubusercontent.com/36569431/36654234-27f5c3ac-1ae1-11e8-8b27-e049e4909c36.jpeg)

**Comment by TJCVRS** [comment]
@niyaz1996 If you just put the entire image into the model it won't be able to recognize the text words
