### ISSUE TITLE
代码有一点问题

### ISSUE THREAD

**Issue by CXY573** [TJCVRS/CRNN_Tensorflow#4]
你好先生，最近在学习tensorflow。我使用了你上传你的代码，但是出现了一些问题，输出的prediction是一些乱码符号，而不是正常的预测。
![2017-10-27 10-45-48](https://user-images.githubusercontent.com/30207116/32085844-095799bc-bb04-11e7-9387-f646e8fd72b6.png)

**Comment by TJCVRS** [comment]
@CXY573 你好，不知道你是否使用的是我新上传的代码，之前修改了字典建立的函数，如果你没有更新仓库的话可能会导致预测失败的问题。你可以参看 #2 。我找到这张图做了测试，结果如下
![test_res](https://user-images.githubusercontent.com/15725187/32086764-fde725f6-bb09-11e7-9dcd-ae49d1d5a1d8.png)，没有出现你遇到的问题。如果还有其他问题欢迎沟通，大家一起修改~

**Comment by CXY573** [comment]
嗯，问题已经解决了，不过import 的路径是绝对路径比如from crnn_model import cnn_basenet 却经常报错，我只能把所有model放在tools里面直接import才能运行。

**Comment by CXY573** [comment]
你好 你有用SVT训练过吗 我不知道怎么转换成tfrecoder。。。

**Comment by TJCVRS** [comment]
@CXY573 关于import的问题，你可以将整个工程的根目录添加进系统环境变量。sys.path.append()。我还没有使用过SVT数据集，关于生成tfrecords，你可以参考tools\write_text_features.py 这是一个生成tfrecords的工具。

**Comment by CXY573** [comment]
你好 我本来想跑一下ICDAR2013的图片集，不过用你的write_text_features.py生成不了tf.record，想问一下你这个文件是针对synth数据集做的吗？？？

**Comment by CXY573** [comment]
好吧 应该也不是针对synth做的 因为明显有路径是train或者test，请问您的程序用的数据集是哪一个 ，可以告知吗，我希望能自己生成tf.record来跑一下程序

**Comment by xrf116** [comment]
@CXY573 训练好后可以共享下数据么？我最近在试着弄中文的

**Comment by TJCVRS** [comment]
@CXY573 我就是用了Synth_90K数据集的子集，可以正常生成tfrecords。你生成不了tfrecords不知道报什么错

**Comment by CXY573** [comment]
嗯，最近在精细研读您的代码，我是高校的研一学生，研究方向是端到端场景文本识别，不过刚入门，所以会出现一些问题，能否直接联系您的私人邮箱，我的邮箱是1391642270@qq.com

**Comment by CXY573** [comment]
如果可以的话，希望能用您的邮箱回复我一下，告知信息，以便后续有一些学术问题的咨询，当然我不会频繁打扰您

**Comment by TJCVRS** [comment]
@CXY573 Ok

**Comment by angelboy000** [comment]
@TJCVRS 你好，在训练过程中，几次迭代后，我的网络输出串都变成了空串，请问这是哪里的问题呢？我的训练数据也是使用write_text_features生成的。我把网络输入的image和ground  truth label都输出，发现是正确的，而且是一一对应的。

**Comment by TJCVRS** [comment]
@angelboy000 这个模型收敛需要比较长的时间

**Comment by angelboy000** [comment]
@TJCVRS 我的准确率一直为0， 有时候loss还会变为inf，请问这是为什么呢？

**Comment by duxiangkun** [comment]
@您好，我的预测输出为空，准确率也为0，请问您知道是怎么回事吗
