### ISSUE TITLE
shadownet_2017-09-29-19-16-33.ckpt-39999 not found

### ISSUE THREAD

**Issue by daoqinzi** [TJCVRS/CRNN_Tensorflow#43]
excute "python tools/test_shadownet.py --dataset_dir data/ --weights_path model/shadownet/shadownet_2017-09-29-19-16-33.ckpt-39999"
however, it turns out "tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for model/shadownet/shadownet_2017-09-29-19-16-33.ckpt-39999"

shadownet_2017-09-29-19-16-33.ckpt-39999 is not in this repo.

**Comment by daoqinzi** [comment]
@TJCVRS i can't get your idear directly, could you please make it more clear to me, or tell me how to do it? Thank you for your help.

**Comment by TJCVRS** [comment]
@daoqinzi You can see the model directory to check the model file

**Comment by daoqinzi** [comment]
@TJCVRS  i get you idear
