### ISSUE TITLE
cpu version

### ISSUE THREAD

**Issue by daoqinzi** [TJCVRS/CRNN_Tensorflow#45]
i saw this"
This software has only been tested on ubuntu 16.04(x64), python3.5, cuda-8.0, cudnn-6.0 with a GTX-1070 GPU"
my question is "does it can be run without gpu?"

**Comment by TJCVRS** [comment]
@daoqinzi The model can be applied on cpu you can change to cpu version with "tf.ConfigProto(device_count={'GPU': 0})"

**Comment by daoqinzi** [comment]
@TJCVRS thank you !!!
