### ISSUE TITLE
Why Chinese Training seq_length is 15 instead of   25

### ISSUE THREAD

**Issue by LXLun** [TJCVRS/CRNN_Tensorflow#49]
and another question , How many Chinese data do you have prepared?

**Comment by LXLun** [comment]
如果我准备了100万数据生成tfrecord的时候会出现内存不够，应该怎样解决？

**Comment by TJCVRS** [comment]
@LXLun 我是分批次写入tfrecords 不要全部写入一个tfrecords

**Comment by LXLun** [comment]
就是用多个tfrecords进行训练？
