### ISSUE TITLE
请问一下支持中文吗？

### ISSUE THREAD

**Issue by xrf116** [TJCVRS/CRNN_Tensorflow#5]
我想用中文进行训练和test，请问现在可以直接用中文进行训练吗

**Comment by TJCVRS** [comment]
@xrf116 中文的训练和测试最近有点忙还没有时间测试，测试好了会上传最新的结果。您要是有什么进展也欢迎讨论，相互学习。

**Comment by CXY573** [comment]
@xrf116 你已经用数据集训练了自己的模型了吗

**Comment by xrf116** [comment]
中文的还没有（准备数据中），目前还在训练英文。自然场景的英文识别率也不高。需要重新训练
