### ISSUE TITLE
请教一下生成tfrecord的问题

### ISSUE THREAD

**Issue by ZhouFangru** [TJCVRS/CRNN_Tensorflow#6]
您好，
我按照readme里的方法生成tfrecord用来测试，结果报错：
OutOfRangeError (see above for traceback): RandomShuffleQueue '_1_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 32, current size 0)
然后我利用write_text_features.py生成的tfrecord，打开以后里面的图片格式为list.每个元素是0到255的像素值。而您在data里自带的tfrecord打开以后是乱码的，应该就是二进制文件。应该如何生成您这样的tfrecord文件呢，您的程序我没有做任何更改。
另外，您的tfrecord文件里面包含8568张图像的名字，但是利用test_shadoenet.py测试的时候输出32张图像的测试结果。这又是为什么呢？
期待您的指导，谢谢！

**Comment by TJCVRS** [comment]
@ZhouFangru test输出只有32张是因为，输出了一个batchsize的数据，你可以修改下代码让它把全部的test结果输出。生成tfrecords报这个错可能是因为你的原始数据中有的图像损坏，无法正常读取，我用这个代码测试生成结果如下图没有问题/home/baidu/Pictures/crnn_tfrecords.jpg。你的数据集文件夹结构可能和我要求的不一致，根目录下需要两个文件夹Train和Test分别存放训练和测试数据，Train和Test文件夹下存放synth数据和sample.txt.。文件树如下所示/home/baidu/Pictures/tree.jpg

**Comment by ZhouFangru** [comment]
您好，
非常感谢您的答复，然后我的文件夹结构和您要求的是一致的。所以我想或许是版本的原因，我是用的TensorFlow1.1以及python2.7。使用该版本是否需要改动某些代码呢？我生成的tfrecords文件如下图所示，图片可以显示成list格式。
![image](https://user-images.githubusercontent.com/24693920/32367420-ffd50244-c0bc-11e7-9143-7ed4f115588b.png)
期待您的指导，谢谢！

**Comment by TJCVRS** [comment]
@ZhouFangru tfrecords无法直接打开查看的 需要解码才能查看 关于tensorflow和python版本可以查看readme文件

**Comment by ZhouFangru** [comment]
谢谢您的答复，tfrecords问题已解决。我现在想要训练中文文本行，但是发现您的json里面的字典没有包含所有的汉字。我在网上也没有找到可以直接用的10位unicode编码字典，请问您有比较完整的字典吗？

**Comment by TJCVRS** [comment]
@ZhouFangru 这个我也没有找到合适的完整字典，之前就找了大概四千个常用汉字，如果你有什么新的发现可以及时交流啊～

**Comment by ZhouFangru** [comment]
四千个已经很多了呀，因为我看您的json文件里面只有537个字符。我连四千个都没有呢还，您可以把您的字典传给吗？

**Comment by ZhouFangru** [comment]
四千个已经很多了呀，因为我看您的json文件里面只有537个字符。我连四千个都没有呢还，您可以把您的字典传给我吗？谢谢啦！

**Comment by TJCVRS** [comment]
@ZhouFangru

**Comment by TJCVRS** [comment]
@ZhouFangru 不好意思，是我弄错了，是常用的500个汉字

**Comment by ZhouFangru** [comment]
哦哦，好的，那我再找找

**Comment by TJCVRS** [comment]
@ZhouFangru 如果找到了欢迎分享给大家

**Comment by ZhouFangru** [comment]
我换了自己的样本以后遇到了新的问题：
tensorflow.python.framework.errors_impl.InvalidArgumentError: Saw a non-null label (index >= num_classes - 1) following a null label, batch: 18 num_classes: 37 labels:
请问这是什么意思呢，num_classes的值设的不对吗？num_classes干什么用的呢？作用是什么呢？

**Comment by TJCVRS** [comment]
@ZhouFangru 我新上传的chinese_versioin_debug的data文件夹里有个比较多的字符集，有三千多个汉字

**Comment by ZhouFangru** [comment]
好的，谢谢您！

**Comment by ZhouFangru** [comment]
可是您好像并没有新上传文件夹啊

**Comment by TJCVRS** [comment]
在chinese version debug分支里有个txt文件

**Comment by angelboy000** [comment]
@ZhouFangru  你好，我想请问一下，你出现的这个问题是怎么解决的呢？

**Comment by ZhouFangru** [comment]
你好，很抱歉，时间太久我不太记得了，我将我更改的代码放在百度网盘里了，链接：https://pan.baidu.com/s/1LyutjHvsTlVUEt2rvhsg4Q 密码：1ey7
希望对你有帮助。

**Comment by maidanglao990** [comment]
@ZhouFangru 我看你训练的数据集挺大的 好像有三百多万张中文图像  你训练了多长时间呢？我这好几天了都没结果

**Comment by ZhouFangru** [comment]
@maidanglao990  大概1周多

**Comment by maidanglao990** [comment]
@ZhouFangru  那我再等等吧  谢谢

**Comment by maidanglao990** [comment]
@ZhouFangru  我想请问一下，我下载了你的训练代码，然后先制作了数据集，其中改了data_utils.py 里面的类别信息，但是我训练的时候出错。
TypeError: Expected float32 passed to parameter 'inputs' of op 'CTCLoss', got (<tf.Tensor 'shadow/cnn_subnetwork/LSTMLayers/transpose_time_major:0' shape=(70, 128, 5991) dtype=float32>,
请问知道什么原因吗？

**Comment by dehaisea** [comment]
@ZhouFangru 你好，请问你是怎么解决的tfrecord的问题，我也遇了了同样的问题

**Comment by Lemonyue** [comment]
@ZhouFangru,您好，请问能否重新上传一下代码到百度网盘？现在不能下载了呢。谢谢！
