### ISSUE TITLE
关于char_dict.json和ord_map.json的疑问

### ISSUE THREAD

**Issue by peterzhou1520** [TJCVRS/CRNN_Tensorflow#60]
你好，我在运行的是master分支的那个项目，按照readme里说的生成了tf文件，用项目自带的.json文件可以成功训练和测试，但是我想训练这个网络只识别数字，所以用chinese_version_debug分支的tools下的establish_char_dict.py生成了char_dict.json和index_2_ord_map.json，把后者改成ord_map.json之后都放回了master分支的char_dict目录下面

生成的char_dict.json如下：
{"48": "0", "49": "1", "50": "2", "51": "3", "52": "4", "53": "5", "54": "6", "55": "7", "56": "8", "57": "9"}

生成的ord_map.json如下：
{"0": "48", "1": "49", "2": "50", "3": "51", "4": "52", "5": "53", "6": "54", "7": "55", "8": "56", "9": "57"}

运行train_shadownet.py之后出现了一下错误：
Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/CRNN_Tensorflow-master/tools/train_shadownet.py", line 179, in <module>
    train_shadownet(args.dataset_dir, args.weights_path)
  File "C:/Users/Administrator/Desktop/CRNN_Tensorflow-master/tools/train_shadownet.py", line 129, in train_shadownet
    preds = decoder.sparse_tensor_to_str(preds[0])
  File "C:\Users\Administrator\Desktop\CRNN_Tensorflow-master\local_utils\data_utils.py", line 141, in sparse_tensor_to_str
    values = np.array([self.__ord_map[str(tmp)] for tmp in values])
  File "C:\Users\Administrator\Desktop\CRNN_Tensorflow-master\local_utils\data_utils.py", line 141, in <listcomp>
    values = np.array([self.__ord_map[str(tmp)] for tmp in values])
KeyError: '34'

最后的keyError不是固定的，还出现过'17','10','24'等数字，请问这个问题要怎么解决呢。

**Comment by TJCVRS** [comment]
@peterzhou1520 这个只要维护一个数字字符到标签的映射关系，你只要按照data文件夹中的char_dict.txt文件组织你自己的数据，然后调用tools里面的脚本这个映射关系就可以自动生成。

**Comment by peterzhou1520** [comment]
你好，我前面就是按照char_dict.txt文件组织的，从0-9就是
0
1
2
.
.
9
这种格式，生成的json文件是
{"48": "0", "49": "1", "50": "2", "51": "3", "52": "4", "53": "5", "54": "6", "55": "7", "56": "8", "57": "9"}
和
{"0": "48", "1": "49", "2": "50", "3": "51", "4": "52", "5": "53", "6": "54", "7": "55", "8": "56", "9": "57"}
但是运行失败

我试了试改了train_shadownet.py里的num_classes，按照0-9再加上一类总共11类
t = crnn_model.ShadowNet(phase='Train', hidden_nums=256, layers_nums=2, seq_length=25, num_classes=11)
现在可以训练了，是不是问题就出在这里呢。

**Comment by frozenscrypt** [comment]
I need to recognise only letters from a to z and numbers from 0 to 9 and nothing else. For this purpose I need to have a mapping for characters that includes only those that I need. How do I generate a char_dict.json and order_map.json. I searched for a char_dict.txt file but couldn't find it. How do I train the network to recognize only the characters that I want.
