### ISSUE TITLE
sample.txt的问题

### ISSUE THREAD

**Issue by DavidGiovatti** [TJCVRS/CRNN_Tensorflow#70]
准备自己的数据集训练时，要提供一个sample.txt的文件存下所有图片路径和标签，请问这个文件怎么得到？我的数据集太大了不可能手打吧……ps我也是准备的Synth 90k 的数据集，我想自己训练一遍试试
谢谢！
@TJCVRS

**Comment by TJCVRS** [comment]
@DavidGiovatti 这个标签数据集是有提供的

**Comment by yingwei13mei** [comment]
请问训练中文的标签数据集可以在哪里获取到？

**Comment by TJCVRS** [comment]
@yingwei13mei 上网搜集常用中文字符集 然后用synethic 方法生成训练样本
