### ISSUE TITLE
There is no model in the folder of  chinese_two_five_merge , how to download Chinese recognition model ?

### ISSUE THREAD

**Issue by bignwei1029** [TJCVRS/CRNN_Tensorflow#72]
how to download the Chinese recogniton  model ? now, when I open the floder  chinese_two_five_merge , the size of the model are only a few KB.

**Comment by TJCVRS** [comment]
@bignwei1029 Once i have spare time i will settle the stuff and upload the model. Thanks

**Comment by haneSier** [comment]
yeah， I need the Chinese recognition model too， hope can download it a few days later

**Comment by TJCVRS** [comment]
@haneSier 有时间以后会上传中文识别模型

**Comment by haneSier** [comment]
训练中文模型，基于无字典转录的话，只要提供训练图片及其对应的标签就可以了吧？ 还有num_classes应该怎么设置（我按着作者你提供的训练自己模型的步骤，出现了一些问题）

**Comment by MaybeShewill-CV** [comment]
@LiuHuiyue666 无字典转录具体是想实现什么功能呢?

**Comment by LiuHuiyue666** [comment]
@MaybeShewill-CV 仍然是单词识别，只是想把字典去掉看看

**Comment by MaybeShewill-CV** [comment]
@LiuHuiyue666 还是没有明白你的意思,我这里的字典只是作为label的一种组织形式用于提供训练数据的ground truth.==!

**Comment by LiuHuiyue666** [comment]
@MaybeShewill-CV 难道不是那种用于拼写检查的词典吗

**Comment by MaybeShewill-CV** [comment]
@LiuHuiyue666 ==! 没明白你在说什么意思。。。。我这个字典只是用来提供char<==>ascii<==>one_hot标签之间的转换关系 你可能哪里误会了这个字典的意思吧

**Comment by LiuHuiyue666** [comment]
@MaybeShewill-CV 哦哦，可能我理解不对，那这个字典可以去掉吗

**Comment by MaybeShewill-CV** [comment]
@LiuHuiyue666 不可以 如果去掉了就没有标签了 但是你如果想换一种方式来维护我上面说的转换关系也是可以的哈

**Comment by LiuHuiyue666** [comment]
@MaybeShewill-CV 你好，不好意思又打扰了，想问一下图片需要自己resize成100*32的吗，还是程序里面自动resize了呢？

**Comment by mdbenito** [comment]
It is automatically resized, but you want to have the original input with a similar aspect ratio of 3:1 so as to not deform it. You can also change the size in `config.py` to whatever suits you, but keep in mind that the maximum sequence length is width/4

**Comment by LiuHuiyue666** [comment]
@mdbenito Thank you very much!
