### ISSUE TITLE
git lfs 相关问题

### ISSUE THREAD

**Issue by Snowty** [TJCVRS/CRNN_Tensorflow#74]
想要fetch chinese version里面的checkpoint，出现以下报错：
![image](https://user-images.githubusercontent.com/10307930/39664147-b0c570f0-50b1-11e8-9e2b-030f1123fa42.png)
想问下是我需要Purchase吗🤣🤣🤣🤣

**Comment by TJCVRS** [comment]
是模型文件太大了 没办法直接push到github…………

**Comment by Snowty** [comment]
@TJCVRS 
第一次见到git lfs，安利给了周围的同学，他们都表示长见识了，嘻嘻😉

**Comment by TJCVRS** [comment]
@Snowty 嗯 否则github不能直接传大于100m的文件

**Comment by bignwei1029** [comment]
@Snowty 我出现跟你一样的问题，你是怎么解决的呢？下载下来了吗？

**Comment by Snowty** [comment]
@bignwei1029    没有下载下来呢🤣

**Comment by gitzxj** [comment]
你好，能不能把中文识别的模型传到百度云上，或者邮箱一下，git lfs太难用了，谢谢！！！！@TJCVRS

**Comment by yingwei13mei** [comment]
我也是上面的报错，报没有quota, 方便放到百度云吗？

**Comment by TJCVRS** [comment]
一有时间会想办法上传的

**Comment by xuannianc** [comment]
@MaybeShewill-CV 你好，请问现在可以下载中文识别的模型吗？
