### ISSUE TITLE
Images with variating width

### ISSUE THREAD

**Issue by samueltin** [TJCVRS/CRNN_Tensorflow#80]
Hello @TJCVRS 
Thank you very much for sharing your model. I am using Chinese branch to train Chinese OCR. I have trained the model with sentences equal to 8 Chinese characters long and achieve quite a good result. Next step, I would like to train longer sentences and sentences with variating length. Thus, the width of the image will be variating as well. Can you give some direction what changes that I should make to make it support images with variating width?

Thank you very much for your help
Samuel

**Comment by TJCVRS** [comment]
@samueltin The model's input need to be a shape fixed image

**Comment by samueltin** [comment]
Thank you very much for your quick response
