### ISSUE TITLE
KeyError：‘65355’

### ISSUE THREAD

**Issue by gydlcc** [TJCVRS/CRNN_Tensorflow#83]
我这个跑得就是 chinese debug version ，就是转换成tfrecord 时出现了这个错误，请问这是怎麽回事 .json里面好像都有我表前的汉字啊
![2018-05-22 22-02-46](https://user-images.githubusercontent.com/26570842/40368241-e7b2ae2a-5e0d-11e8-8b43-a8f710130006.png)

然后下面是我的samples.txt

![2018-05-22 22-18-29](https://user-images.githubusercontent.com/26570842/40368329-1e942428-5e0e-11e8-90f2-45135285a4fe.png)

**Comment by mialrr** [comment]
文件名称 需要写入中文

**Comment by gydlcc** [comment]
@mialrr 
哪里需要写入中文，没听明白

**Comment by mialrr** [comment]
我看错了  我以为是之前的版本  不好意思
