### ISSUE TITLE
loss一直在震荡

### ISSUE THREAD

**Issue by hustzxl** [TJCVRS/CRNN_Tensorflow#90]
准确的是说loss一直没有变化，我使用@TJCVRS 提供的模型作为预训练模型，第一次迭代的时候accuracy = 0.89.然后一直跌到到40000，accuracy一直在0.89到0.92之间变化，loss曲线也是一直震荡

**Comment by TJCVRS** [comment]
@hustzxl It will be a long time before the model converge
